name: CI

on:
  push:
    branches: [ githubaction ]
  pull_request:
    branches: [ githubaction ]
  workflow_dispatch:

jobs:
  Build_And_Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}

    - name: Restore node_modules from cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: npm ci
      
# gitleaks check from code have secrets 
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITLEAKS_API_TOKEN }}
    # ---- Linting ----
    - name: Run lint check
      run: npm run lint
      continue-on-error: true

    - name: Run lint fix
      run: npm run lint:fix || true
      if: always()

    - name: Run tests (JUnit)
      run: npm run test:ci

    - name: Upload JUnit report
      uses: actions/upload-artifact@v4
      with:
        name: junit-report
        path: reports/junit/junit.xml
        if-no-files-found: warn


    # Upload test reports even if tests failed
    - name: Upload test results & coverage
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          coverage/
          test-results/
          junit.xml
      # if: always()

    # ---- Build (only if everything passed) ----
    - name: Build
      if: success()
      run: npm run build
